Configuratron:
  use_only:
    - mmidb
    - bci_iv_2a
    - ern
    - erpbci
    - sleep-edf
  preload: True
  sfreq: 256
  deep1010:
    return_mask: False

encoder_weights: C:\Users\chedl\OneDrive\Bureau\EMSE\3A\PE\encoder.pt
context_weights: C:\Users\chedl\OneDrive\Bureau\EMSE\3A\PE\contextualizer.pt

datasets: !include configs/downstream_datasets.yml