mmidb:
  name: "Physionet MMIDB"
  toplevel: "C:\\Users\\chedl\\OneDrive\\Bureau\\EMSE\\3A\\PE\\files"
  tmin: 0
  tlen: 6
  data_max: 0.001
  data_min: -0.001
  events:
    - T1
    - T2
  exclude_sessions:
    - "*R0[!48].edf"  # equivalently "*R0[1235679].edf"
    - "*R1[!2].edf"   # equivalently "*R1[134].edf"
  exclude_people:
    - S088
    - S090
    - S092
    - S100
  train_params:
    epochs: 7
    batch_size: 4 # I find this dataset likes small batch sizes
  lr: 0.00001
  folds: 5

mahnob_eeg:
  name: "EEG MAHNOB"
  toplevel: "C:\\Users\\chedl\\OneDrive\\Bureau\\EMSE\\3A\\PE\\test"
  tlen: 120
  #tmin: 0
  #targets: 79
  events:
    'valence_0': 0
    'valence_1': 1
  train_params:
    epochs: 3
    batch_size: 60
  lr: 0.00005

bouli:
  name: "bibou"
  toplevel: "/mnt/c/Users/chedl/OneDrive/Bureau/EMSE/3A/PE/test"
  tmin: -2
  tlen: 6
  extensions:
    - .edf
  train_params:
    epochs: 3
    batch_size: 60
    lr: 0.00005

sleep-edf:
  name: "Sleep EDFx Cassette"
  filename_format: "SC4{subject:2}{session:1}"
  annotation_format: "SC4{subject:2}{session:1}*Hypnogram*"
  toplevel: "C:\\Users\\chedl\\OneDrive\\Bureau\\EMSE\\3A\\PE\\SSC\\sleep-cassette"
  tmin: 0
  tlen: 30
  data_max: 0.001
  data_min: -0.001
  extensions:
    - .edf
  chunk_duration: 30
  events:
    'Sleep stage W': 0
    'Sleep stage 1': 1
    'Sleep stage 2': 2
    'Sleep stage 3': 3
    'Sleep stage 4': 3
    'Sleep stage R': 4
  rename_channels:
    FPZ: 'EEG Fpz-Cz'
    PZ: 'EEG Pz-Oz'
    HEOGL: "EOG horizontal"
  picks:
    - eeg
  exclude_channels:
    - "Resp oro-nasal"
    - 'EMG submental'
    - 'Temp rectal' # Comfiest sleep ever
    - 'Event marker'
  train_params:
    epochs: 40
    batch_size: 80
    balance_method: undersample
    validation_interval: 1000
  lr: 0.00005
  folds: 10

erpbci:
  data_max: 0.00631
  data_min: -0.00283
  toplevel: "C:\\Users\\chedl\\OneDrive\\Bureau\\EMSE\\3A\\PE\\erp"
  tmin: -0.1
  tlen: 0.7
  # We low-passed offline using this parameter just so it didn't happen over and over.
  # Uncommenting this and part of LoaderERPBCI in dn3_ext.py should reproduce the same results (it says where)
  lpf: 120
  extensions:
  # Swap the following for using default dataset
    - .edf
#    - .fif
  picks:
    - eeg
  events:
    - 1
    - 2
  exclude_people:
    - s08
    - s12
    - s10
    # This stronge person shouldn't affect anyone else, if it does just comment them out
    - BENDR
  train_params:
    epochs: 20
    batch_size: 64
    balance_method: undersample
  lr: 0.00001


