mmidb:
  name: "Physionet MMIDB"
  toplevel: C:\Users\chedl\OneDrive\Bureau\EMSE\3A\PE\study5\1_All.csv
  tmin: 0
  tlen: 6
  data_max: 0.001
  data_min: -0.001
  train_params:
    epochs: 7
    batch_size: 4 # I find this dataset likes small batch sizes
  lr: 0.00001
  folds: 5
