Configuratron:
  use_only:
    - bci_iv_2a
    - bci_iv_2a
    - bci_iv_2a
  samples: 15360 # = 60 seconds
  sfreq: 256
  deep1010:
    return_mask: True

validation_dataset: bci_iv_2a

augmentation_params:
  upsample_crop: 32
  batch_crop_frac: 0.05

training_params:
  epochs: 1
  validation_interval: 100
  train_log_interval: 100
  batch_size: 64
  warmup_frac: 0.05

mask_threshold: 0.85
mask_inflation: 1.
mask_pct_max: 0.6

optimizer_params:
  lr: 0.00002
  weight_decay: 0.01
  betas: [0.9, 0.98]

bending_college_args:
  mask_rate: 0.065
  mask_span: 10
  layer_drop: 0.01
  multi_gpu: True
  temp: 0.1
  encoder_grad_frac: 0.1
  num_negatives: 20
  enc_feat_l2: 1.0

datasets:

  bci_iv_2a:
    name: "BCI Competition IV 2a"
    toplevel: "/mnt/c/Users/chedl/OneDrive/Bureau/EMSE/3A/PE/data"
    stride: 1536
    data_max: 100
    data_min: -100
    extensions:
      - .raw.fif
    picks:
      - eeg
    exclude_sessions:
      - "*E*"
