bci_iv_2a:
  name: "Physionet MMIDB"
  toplevel: /mnt/c/Users/chedl/OneDrive/Bureau/EMSE/3A/PE/essai/S001
  stride: 15360
  data_max: 0.001
  data_min: -0.001
  exclude_people:
    - S088
    - S090
    - S092
    - S100

